=== Identityhub/vc-jsonschema/dist/schemas/18-weirdoghostgang-holder/1-1-0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/18-weirdoghostgang-holder/1-1-0.json",
  "title": "WeirdoGhostGang Holder",
  "description": "You are WeirdoGhostGang NFT holder",
  "type": "object",
  "required": [
    "@context",
    "issuer",
    "issuanceDate",
    "credentialSubject",
    "proof"
  ],
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "type": "object",
      "required": [
        "id",
        "name",
        "mrenclave"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "mrenclave": {
          "type": "string"
        },
        "runtimeVersion": {
          "type": "object",
          "required": [
            "parachain",
            "sidechain"
          ],
          "properties": {
            "sidechain": {
              "type": "string"
            },
            "parachain": {
              "type": "string"
            }
          }
        }
      }
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time"
    },
    "proof": {
      "type": "object",
      "required": [
        "created",
        "type",
        "proofPurpose",
        "proofValue",
        "verificationMethod"
      ],
      "properties": {
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "type": "string"
        },
        "proofPurpose": {
          "type": "string"
        },
        "proofValue": {
          "type": "string"
        },
        "verificationMethod": {
          "type": "string"
        }
      }
    },
    "credentialSubject": {
      "title": "Credential Subject of NodeReal/ WeirdoGhostGang Holder",
      "type": "object",
      "required": [
        "id",
        "type",
        "values",
        "endpoint",
        "assertions"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "boolean"
          }
        },
        "endpoint": {
          "type": "string",
          "format": "uri"
        },
        "assertions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "src",
              "op",
              "dst"
            ],
            "properties": {
              "src": {
                "type": "string",
                "enum": [
                  "$is_weirdo_ghost_gang_holder"
                ]
              },
              "op": {
                "type": "string",
                "enum": [
                  "=="
                ]
              },
              "dst": {
                "type": "string",
                "enum": [
                  "true"
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== Identityhub/vc-jsonschema/examples/20-weirdoghostgang-holder/weirdoghostgang-holder.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xe0c8b1b07a108347df0ce548224ac9e018604f49444d8ac5580bad9cbf752c7b",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x52a6c52dc82940a36fefd1474cc0778517bb1a56b7bda0e308b6c19152dd7510",
    "description": "You are WeirdoGhostGang NFT holder",
    "type": "WeirdoGhostGang Holder",
    "assertions": [
      { "src": "$is_weirdo_ghost_gang_holder", "op": "==", "dst": "true" }
    ],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p"
  },
  "issuanceDate": "2023-12-27T21:01:54.065425159+00:00",
  "proof": {
    "created": "2023-12-27T21:01:54.065885623+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}
