=== Identityhub/vc-jsonschema/dist/schemas/14-generic-discord-role/1-1-0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/14-generic-discord-role/1-1-0.json",
  "title": "You have certain role on Litentry Official Discord Server.",
  "description": "You have a role that entitles you as \"Litentry & Contest Legend\", \"Litentry & Popularity Award of Score Contest\", \"Litentry & Contest Participant\", \"Litentry & SORA Quiz Attendee\", or \"Litentry & SORA Quiz Master\"",
  "type": "object",
  "required": [
    "@context",
    "issuer",
    "issuanceDate",
    "credentialSubject",
    "proof"
  ],
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "type": "object",
      "required": [
        "id",
        "name",
        "mrenclave"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "mrenclave": {
          "type": "string"
        }
      }
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time"
    },
    "proof": {
      "type": "object",
      "required": [
        "created",
        "type",
        "proofPurpose",
        "proofValue",
        "verificationMethod"
      ],
      "properties": {
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "type": "string"
        },
        "proofPurpose": {
          "type": "string"
        },
        "proofValue": {
          "type": "string"
        },
        "verificationMethod": {
          "type": "string"
        }
      }
    },
    "credentialSubject": {
      "title": "Credential Subject of GenericDiscordRole/ Litentry Discord Contests/ Litentry & SORA Quiz",
      "type": "object",
      "required": [
        "id",
        "type",
        "values",
        "endpoint",
        "assertions"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "boolean"
          }
        },
        "endpoint": {
          "type": "string",
          "format": "uri"
        },
        "assertions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "src",
              "op",
              "dst"
            ],
            "properties": {
              "src": {
                "type": "string",
                "enum": [
                  "$is_contest_legend",
                  "$is_contest_popularity",
                  "$is_contest_participant",
                  "$is_attendee",
                  "$is_master"
                ]
              },
              "op": {
                "type": "string",
                "enum": [
                  "=="
                ]
              },
              "dst": {
                "type": "string",
                "enum": [
                  "true"
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== Identityhub/vc-jsonschema/examples/1-1-0/14-generic-discord-role/generic-discord-role-soraquiz-master.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x081cf96c620fcc97d6aeab0df473e5d474db70a4c45877b8b396b63a6f895c6f",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x3a2647fe0ecd1fe0d450fd8650cd8bf3536ecac77b6e8ec2df1b5f5fc9d62931",
    "description": "Congratulations on winning our first quiz in collaboration with Sora! By emerging as the winner, you have shown your excellent understanding of DeFi along with Web3 identity security and privacy. You are truly a champion in this field!",
    "type": "Litentry & SORA Quiz Master",
    "assertions": [{ "src": "$is_master", "op": "==", "dst": "true" }],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p",
    "runtimeVersion": {
      "parachain": 9174,
      "sidechain": 104
    }
  },
  "issuanceDate": "2023-12-27T17:28:12.128591524+00:00",
  "proof": {
    "created": "2023-12-27T17:28:12.129086512+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}

=== Identityhub/vc-jsonschema/examples/14-generic-discord-role/generic-discord-role-contest-legend.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xf275c2e31cae9462b6ca923fb5059c164c4b90b67a77e4160e40f7d69546a865",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x3a2647fe0ecd1fe0d450fd8650cd8bf3536ecac77b6e8ec2df1b5f5fc9d62931",
    "description": "You got the Top Award of community contest.",
    "type": "Litentry & Contest Legend",
    "assertions": [{ "src": "$is_contest_legend", "op": "==", "dst": "true" }],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p"
  },
  "issuanceDate": "2023-12-27T17:23:54.057204342+00:00",
  "proof": {
    "created": "2023-12-27T17:23:54.057701918+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}

=== Identityhub/vc-jsonschema/examples/14-generic-discord-role/generic-discord-role-soraquiz-attendee.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xc03975489ae1df6e8a202856ac945a306b8a4c5eb5dca75ebe467adbdb6d88a9",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x3a2647fe0ecd1fe0d450fd8650cd8bf3536ecac77b6e8ec2df1b5f5fc9d62931",
    "description": "Congratulations on your participation in our first quiz in collaboration with our partner, Sora. You have embarked on an exciting educational journey, exploring the world of DeFi & Web3 Identity, we truly appreciate your curiosity and dedication.",
    "type": "Litentry & SORA Quiz Attendee",
    "assertions": [{ "src": "$is_attendee", "op": "==", "dst": "true" }],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p"
  },
  "issuanceDate": "2023-12-27T17:27:12.111359985+00:00",
  "proof": {
    "created": "2023-12-27T17:27:12.111781055+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}

=== Identityhub/vc-jsonschema/examples/1-0-0/14-generic-discord-role/generic-discord-role-contest-popularity.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x43e4f8908c32e50a9a08645241a558d57ede2dbfc95a30f9257e844ef441d633",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x3a2647fe0ecd1fe0d450fd8650cd8bf3536ecac77b6e8ec2df1b5f5fc9d62931",
    "description": "You got the Popularity Award of community contest.",
    "type": "Litentry & Popularity Award of Score Contest",
    "assertions": [
      { "src": "$is_contest_popularity", "op": "==", "dst": "true" }
    ],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p"
  },
  "issuanceDate": "2023-12-27T17:25:00.150406618+00:00",
  "proof": {
    "created": "2023-12-27T17:25:00.150831108+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}

=== Identityhub/vc-jsonschema/examples/14-generic-discord-role/generic-discord-role-contest-popularity-participant.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xe0dbdfd87b3cc7f7dc1a98b50388f6f4dc1da82425007834f113d1e87d84dc65",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x3a2647fe0ecd1fe0d450fd8650cd8bf3536ecac77b6e8ec2df1b5f5fc9d62931",
    "description": "You participated in the community contest.",
    "type": "Litentry & Contest Participant",
    "assertions": [
      { "src": "$is_contest_participant", "op": "==", "dst": "true" }
    ],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2",
    "name": "Litentry TEE Worker",
    "mrenclave": "MsSostcy6BCmtFzk4DGuXxqQsnqXx9EgKCZ6vHLts2p"
  },
  "issuanceDate": "2023-12-27T17:25:48.131330048+00:00",
  "proof": {
    "created": "2023-12-27T17:25:48.131748956+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "45ac723de934358c79826cf2c8f2e92429ee1d59bc7069dc0026bf7116135d519cc9cd88ec4bda6213138686e44e00b7d1bfcbdfe047c4c30412af77bf890808",
    "verificationMethod": "0xd2ca10cdb1886f99f72273aa502357dfe60b8a16d0e94974c988cf19546facc2"
  }
}
