=== Identityhub/vc-jsonschema/dist/schemas/1-basic-identity-verification/1-0-0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/1-basic-identity-verification/1-0-0.json",
  "title": "Basic Identity Verification",
  "description": "You've identified at least one account/address in both Web2 and Web3.",
  "type": "object",
  "required": [
    "@context",
    "issuer",
    "issuanceDate",
    "credentialSubject",
    "proof"
  ],
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "type": "object",
      "required": [
        "id",
        "name",
        "mrenclave"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "mrenclave": {
          "type": "string"
        }
      }
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time"
    },
    "proof": {
      "type": "object",
      "required": [
        "created",
        "type",
        "proofPurpose",
        "proofValue",
        "verificationMethod"
      ],
      "properties": {
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "type": "string"
        },
        "proofPurpose": {
          "type": "string"
        },
        "proofValue": {
          "type": "string"
        },
        "verificationMethod": {
          "type": "string"
        }
      }
    },
    "credentialSubject": {
      "title": "Credential Subject of A1 assertion/ Basic Identity Verification",
      "type": "object",
      "required": [
        "id",
        "type",
        "values",
        "endpoint",
        "assertions"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "boolean"
          }
        },
        "endpoint": {
          "type": "string",
          "format": "uri"
        },
        "assertions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "and"
            ],
            "properties": {
              "and": {
                "type": "array",
                "minItems": 2,
                "maxItems": 2,
                "additionalItems": false,
                "items": [
                  {
                    "type": "object",
                    "required": [
                      "src",
                      "op",
                      "dst"
                    ],
                    "properties": {
                      "src": {
                        "type": "string",
                        "enum": [
                          "$has_web2_account"
                        ]
                      },
                      "op": {
                        "type": "string",
                        "enum": [
                          "=="
                        ]
                      },
                      "dst": {
                        "type": "string",
                        "enum": [
                          "true"
                        ]
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "src",
                      "op",
                      "dst"
                    ],
                    "properties": {
                      "src": {
                        "type": "string",
                        "enum": [
                          "$has_web3_account"
                        ]
                      },
                      "op": {
                        "type": "string",
                        "enum": [
                          "=="
                        ]
                      },
                      "dst": {
                        "type": "string",
                        "enum": [
                          "true"
                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== Identityhub/vc-jsonschema/examples/achainable/class_of_year.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0xf4787b47819a21b475aa0e46b2bf1d2f4f1adda28de6a37d47acc584e4632754",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"The class of year that the user account was created on a particular network (must have on-chain records)",
        "type":"Account Class Of Year",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$account_created_year",
                        "op":"==",
                        "dst":"Invalid"
                    }
                ]
            }
        ],
        "values":[
            false
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"3730028d06f5cad69891d61a198a7b4495ff5fbaf6203df6b12fbf37e5336952",
        "name":"Litentry TEE Worker",
        "mrenclave":"ELzBHDP2T1TfYpD3ES3zBeRN43X9AmUC2cFqtckbynTP"
    },
    "issuanceDate":"2023-08-05T10:20:12.355000681+00:00",
    "proof":{
        "created":"2023-08-05T10:20:12.356444202+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"666a2d3c8163019fe9e2de38c40896e3a4e1eada0cc1d4e335c1877e497557a1b3cadc9282b1b9cacaec949ee13191cd386a97f7b0f4c14201a87a01c8621402",
        "verificationMethod":"3730028d06f5cad69891d61a198a7b4495ff5fbaf6203df6b12fbf37e5336952"
    }
}

=== Identityhub/vc-jsonschema/example/a3/a3.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0x8798dbc0a812d235f7d136e599dd33fda6cee0f6d3b2c66f8093a5c2ddd41bf0",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"You have commented in Litentry Discord #ðŸª‚id-hubber channel. Channel link: https://discord.com/channels/807161594245152800/1093886939746291882",
        "type":"Active Discord ID-Hubber",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$has_role",
                        "op":"==",
                        "dst":"true"
                    },
                    {
                        "src":"$has_commented",
                        "op":"==",
                        "dst":"true"
                    },
                    {
                        "src":"$discord_guild_id",
                        "op":"==",
                        "dst":"10"
                    },
                    {
                        "src":"$discord_channel_id",
                        "op":"==",
                        "dst":"10"
                    },
                    {
                        "src":"$discord_role_id",
                        "op":"==",
                        "dst":"10"
                    }
                ]
            }
        ],
        "values":[
            false
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
        "name":"Litentry TEE Worker",
        "mrenclave":"6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59"
    },
    "issuanceDate":"2023-09-26T02:45:42.341318167+00:00",
    "proof":{
        "created":"2023-09-26T02:45:42.341636083+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
        "verificationMethod":"28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
    }
}

=== Identityhub/vc-jsonschema/examples/1-1-0/4-token-holding-time/token-holding-time-a4-lit.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xd4fca1d70259b19eef4649e86c946331a8d15dfeb54bfaf88518f1fa14a39248",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
    "description": "The length of time a user continues to hold a particular token (with particular threshold of token amount)",
    "type": "LIT Holding Time",
    "assertions": [
      {
        "and": [
          {
            "src": "$minimum_amount",
            "op": "==",
            "dst": "10"
          },
          {
            "src": "$from_date",
            "op": "<",
            "dst": "2017-01-01"
          },
          {
            "src": "$to_date",
            "op": ">=",
            "dst": "2023-09-26"
          }
        ]
      }
    ],
    "values": [true],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
    "name": "Litentry TEE Worker",
    "mrenclave": "6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59",
    "runtimeVersion": {
      "parachain": 9174,
      "sidechain": 104
    }
  },
  "issuanceDate": "2023-09-26T02:47:06.480235979+00:00",
  "proof": {
    "created": "2023-09-26T02:47:06.480756337+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
    "verificationMethod": "28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
  }
}
