=== Identityhub/vc-jsonschema/dist/schemas/1-basic-identity-verification/1-0-0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/litentry/vc-jsonschema/main/dist/schemas/1-basic-identity-verification/1-0-0.json",
  "title": "Basic Identity Verification",
  "description": "You've identified at least one account/address in both Web2 and Web3.",
  "type": "object",
  "required": [
    "@context",
    "issuer",
    "issuanceDate",
    "credentialSubject",
    "proof"
  ],
  "properties": {
    "@context": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "id": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "issuer": {
      "type": "object",
      "required": [
        "id",
        "name",
        "mrenclave"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "mrenclave": {
          "type": "string"
        }
      }
    },
    "issuanceDate": {
      "type": "string",
      "format": "date-time"
    },
    "proof": {
      "type": "object",
      "required": [
        "created",
        "type",
        "proofPurpose",
        "proofValue",
        "verificationMethod"
      ],
      "properties": {
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "type": {
          "type": "string"
        },
        "proofPurpose": {
          "type": "string"
        },
        "proofValue": {
          "type": "string"
        },
        "verificationMethod": {
          "type": "string"
        }
      }
    },
    "credentialSubject": {
      "title": "Credential Subject of A1 assertion/ Basic Identity Verification",
      "type": "object",
      "required": [
        "id",
        "type",
        "values",
        "endpoint",
        "assertions"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "values": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "boolean"
          }
        },
        "endpoint": {
          "type": "string",
          "format": "uri"
        },
        "assertions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [
              "and"
            ],
            "properties": {
              "and": {
                "type": "array",
                "minItems": 2,
                "maxItems": 2,
                "additionalItems": false,
                "items": [
                  {
                    "type": "object",
                    "required": [
                      "src",
                      "op",
                      "dst"
                    ],
                    "properties": {
                      "src": {
                        "type": "string",
                        "enum": [
                          "$has_web2_account"
                        ]
                      },
                      "op": {
                        "type": "string",
                        "enum": [
                          "=="
                        ]
                      },
                      "dst": {
                        "type": "string",
                        "enum": [
                          "true"
                        ]
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "src",
                      "op",
                      "dst"
                    ],
                    "properties": {
                      "src": {
                        "type": "string",
                        "enum": [
                          "$has_web3_account"
                        ]
                      },
                      "op": {
                        "type": "string",
                        "enum": [
                          "=="
                        ]
                      },
                      "dst": {
                        "type": "string",
                        "enum": [
                          "true"
                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}

=== Identityhub/vc-jsonschema/example/achainable/uniswap_v2_v3_user.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0x3345a013b3025a4082025459a468d85c22c4664b2186fca6b901efba94f07065",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"You are a trader or liquidity provider of Uniswap V2 or V3. \n\tUniswap V2 Factory Contract: 0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f. \n\tUniswap V3 Factory Contract: 0x1f98431c8ad98523631ae4a59f267346ea31f984.",
        "type":"Uniswap V2/V3 User",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$is_uniswap_v2_user",
                        "op":"==",
                        "dst":"true"
                    },
                    {
                        "src":"$is_uniswap_v3_user",
                        "op":"==",
                        "dst":"true"
                    }
                ]
            }
        ],
        "values":[
            true
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x9282e646c6d22c4bfeb0762518e60a83d6a5bd34699d288a82ca5f44fc42c2e3",
        "name":"Litentry TEE Worker",
        "mrenclave":"BaSJUyn61a2BUWu6Fd4VqzjUZ4b5rQWUMew1nR536uZ2"
    },
    "issuanceDate":"2023-08-10T12:30:35.538750458+00:00",
    "proof":{
        "created":"2023-08-10T12:30:35.542729427+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"53c114212b174e75df2c44807537b2c0c9af058667f0949b6fe39f3e8ba20497b245434a9b37cfe8335cd45bbc88ee6e1b6ec725202afd2da4b7deb9cded1704",
        "verificationMethod":"9282e646c6d22c4bfeb0762518e60a83d6a5bd34699d288a82ca5f44fc42c2e3"
    }
}

=== Identityhub/vc-jsonschema/example/a6/a6.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0xe44735a353a956c4bf7134777c864295faa03e439e375987deb4e1a45ea4f782",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"The range of the user's Twitter follower count",
        "type":"Twitter Follower Amount",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$total_followers",
                        "op":">",
                        "dst":"0"
                    },
                    {
                        "src":"$total_followers",
                        "op":"<=",
                        "dst":"1"
                    }
                ]
            }
        ],
        "values":[
            true
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
        "name":"Litentry TEE Worker",
        "mrenclave":"6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59"
    },
    "issuanceDate":"2023-09-26T02:48:30.496753869+00:00",
    "proof":{
        "created":"2023-09-26T02:48:30.497371209+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
        "verificationMethod":"28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
    }
}

=== Identityhub/vc-jsonschema/example/a2/a2.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0xbba3d3fbbda2e26f911a481d764bbb4d6c334d260033154b5bb267c98c54da58",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"The user is a member of Litentry Discord. \nServer link: https://discord.gg/phBSa3eMX9\nGuild ID: 807161594245152800.",
        "type":"Litentry Discord Member",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$verified_discord_account",
                        "op":">",
                        "dst":"0"
                    },
                    {
                        "src":"$has_joined",
                        "op":"==",
                        "dst":"true"
                    },
                    {
                        "src":"$discord_guild_id",
                        "op":"==",
                        "dst":"abc"
                    }
                ]
            }
        ],
        "values":[
            false
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
        "name":"Litentry TEE Worker",
        "mrenclave":"6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59"
    },
    "issuanceDate":"2023-09-26T02:43:42.331230110+00:00",
    "proof":{
        "created":"2023-09-26T02:43:42.331528147+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
        "verificationMethod":"28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
    }
}

=== Identityhub/vc-jsonschema/examples/a1/a1.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0x7a9e038f30e90e5f5dff366a3a8b98d3797fb9747691571a499dcd78d4a8e014",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"You've identified at least one account/address in both Web2 and Web3.",
        "type":"Basic Identity Verification",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$has_web2_account",
                        "op":"==",
                        "dst":"true"
                    },
                    {
                        "src":"$has_web3_account",
                        "op":"==",
                        "dst":"true"
                    }
                ]
            }
        ],
        "values":[
            false
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
        "name":"Litentry TEE Worker",
        "mrenclave":"6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59"
    },
    "issuanceDate":"2023-09-26T02:41:54.471751195+00:00",
    "proof":{
        "created":"2023-09-26T02:41:54.472164087+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
        "verificationMethod":"28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
    }
}

=== Identityhub/vc-jsonschema/examples/1-1-0/7-evm-substrate-transaction-count/a8.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x0d3f27cf78b7f72f2d9b7dca4727c58043be6d5763a3151f4edaa15b12ca3c90",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
    "description": "Gets the range of number of transactions a user has made for a specific token on all supported networks (invalid transactions are also counted)",
    "type": "EVM/Substrate Transaction Count",
    "assertions": [
      {
        "and": [
          {
            "src": "$total_txs",
            "op": ">=",
            "dst": "20"
          },
          {
            "src": "$total_txs",
            "op": "<",
            "dst": "50"
          },
          {
            "or": [
              {
                "src": "$network",
                "op": "==",
                "dst": "Polkadot"
              }
            ]
          }
        ]
      }
    ],
    "values": [true],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
    "name": "Litentry TEE Worker",
    "mrenclave": "6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59",
    "runtimeVersion": {
      "parachain": 9174,
      "sidechain": 104
    }
  },
  "issuanceDate": "2023-09-26T02:50:42.312362493+00:00",
  "proof": {
    "created": "2023-09-26T02:50:42.312641669+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
    "verificationMethod": "28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
  }
}

=== Identityhub/vc-jsonschema/examples/1-1-0/11-token-holder/token-holder-eth.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0xa7fa12909d8a680c88e6dedf50dc54c9a9de82f33f6030972677d6ef7c458b27",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
    "description": "Token Holder",
    "type": "The number of a particular token you hold > 0",
    "assertions": [
      {
        "and": [
          {
            "src": "$is_eth_holder",
            "op": "==",
            "dst": "true"
          }
        ]
      }
    ],
    "values": [true],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "3730028d06f5cad69891d61a198a7b4495ff5fbaf6203df6b12fbf37e5336952",
    "name": "Litentry TEE Worker",
    "mrenclave": "GfMyFWNrjf5AzSZhivryouT8SyyJ1mUfkJujjirtQuvE",
    "runtimeVersion": {
      "parachain": 9174,
      "sidechain": 104
    }
  },
  "issuanceDate": "2023-08-05T11:12:18.316012589+00:00",
  "proof": {
    "created": "2023-08-05T11:12:18.318187272+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "9c763812bddb91129b4be8270f218b5e5fd2885697d5b6710493929746c9ed91b7dc329030c72599b84f2bab6ad410e53744023bf5f248ef08c7f2779fbece0c",
    "verificationMethod": "3730028d06f5cad69891d61a198a7b4495ff5fbaf6203df6b12fbf37e5336952"
  }
}

=== Identityhub/vc-jsonschema/example/a11/a11.json
{
    "@context":[
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id":"0xcb4236039f53af617430c633b632c91f3d8994c4a8d2204aa92ed832e63685d5",
    "type":[
        "VerifiableCredential"
    ],
    "credentialSubject":{
        "id":"did:litentry:substrate:0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d",
        "description":"The length of time a user continues to hold a particular token (with particular threshold of token amount)",
        "type":"ETH Holding Time",
        "assertions":[
            {
                "and":[
                    {
                        "src":"$minimum_amount",
                        "op":"==",
                        "dst":"10"
                    },
                    {
                        "src":"$from_date",
                        "op":"<",
                        "dst":"2017-01-01"
                    },
                    {
                        "src":"$to_date",
                        "op":">=",
                        "dst":"2023-09-26"
                    }
                ]
            }
        ],
        "values":[
            false
        ],
        "endpoint":"http://localhost:9933"
    },
    "issuer":{
        "id":"did:litentry:substrate:0x28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135",
        "name":"Litentry TEE Worker",
        "mrenclave":"6cgJxACaf91s7CvoA6fVYUHpvFKLrEDe3mLJHDND6t59"
    },
    "issuanceDate":"2023-09-26T03:48:00.456139284+00:00",
    "proof":{
        "created":"2023-09-26T03:48:00.456425831+00:00",
        "type":"Ed25519Signature2020",
        "proofPurpose":"assertionMethod",
        "proofValue":"25ff768780046ad249c2d853b9d442850199304221b78f3da99e0aac946a627702927262db5cef1a5411cba82c0925359fd31b0bac1771eb28c71b271bec9f0b",
        "verificationMethod":"28d3b174041231100f3bea49444fb44b5ee500a463b2d26ff7e6dc5d98f15135"
    }
}

=== Identityhub/vc-jsonschema/examples/7-evm-substrate-transaction-count/a8.2.json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "id": "0x6d576c95cef6442d030ce578c601c67c15d3d2887ee9ccb147e109db80a586d4",
  "type": ["VerifiableCredential"],
  "credentialSubject": {
    "id": "did:litentry:substrate:0x8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48",
    "description": "Gets the range of number of transactions a user has made for a specific token on all supported networks (invalid transactions are also counted)",
    "type": "EVM/Substrate Transaction Count",
    "assertions": [
      {
        "and": [
          { "src": "$total_txs", "op": ">=", "dst": "0" },
          { "src": "$total_txs", "op": "<", "dst": "1" },
          {
            "or": [
              { "src": "$network", "op": "==", "dst": "Litentry" },
              { "src": "$network", "op": "==", "dst": "Litmus" }
            ]
          }
        ]
      }
    ],
    "values": [false],
    "endpoint": "http://localhost:9933"
  },
  "issuer": {
    "id": "did:litentry:substrate:0xf9a07bf94ba238abc2eec2d83e21e3800a7f58e4490a23be583e41f6d200f47f",
    "name": "Litentry TEE Worker",
    "mrenclave": "7abeD7UnAo9TMe6Rz7tva5B1ZVEbZbCEuQ4bnBr32QH"
  },
  "issuanceDate": "2023-12-14T18:35:12.128795174+00:00",
  "proof": {
    "created": "2023-12-14T18:35:12.129307699+00:00",
    "type": "Ed25519Signature2020",
    "proofPurpose": "assertionMethod",
    "proofValue": "794b3f5d248c6109aa5aa43b4b294a6d892db5fa54f674362ee2fd17e1f2c5da3a650d358711ed6224de2babcf0ce83db1945d5bb34ac9a4e611271d23682609",
    "verificationMethod": "0xf9a07bf94ba238abc2eec2d83e21e3800a7f58e4490a23be583e41f6d200f47f"
  }
}
